import Head from 'next/head';
import styles from '@/styles/Home.module.css';
import Btn from '@/components/button/Btn';
import ProductCardContainer from '@/components/productCardContainer/ProductCardContainer';
import Image from 'next/image';
import BestGear from '@/components/bestGear/BestGear';

export default function Home() {
  return (
    <>
      <Head>
        <title>Audiophile</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/icon.png" />
      </Head>
      <main>
        <section className={`${styles.homeContainer}`}>
          <div className={`${styles.home} center childsMargin margin`}>
            <strong className={styles.newProduct}>NEW PRODUCT</strong>
            <h1 className={styles.white}>XX99 MARK || <br /> HEADPHONES</h1>
            <p style={{ color: 'var(--grey)' }}>Experience natural, lifelike audio and exceptional build quality made for the passionate music enthusiast.</p>
            <Btn bg={"orange"} size={'large'} text={'SEE PRODUCT'} />
          </div>
        </section>
        <section className={`${styles.productShow} margin`}>
          <ProductCardContainer />
        </section>
        <section className={`${styles.zx9SpeakerContainer} marginTB b-radius`}>
          <div className={`${styles.zx9Speaker} center width100 height100`}>
            <div className="center">
              <Image className={styles.zx9} src="/images/home/desktop/image-speaker-zx9.png" width={500} height={500} />
            </div>
            <div className={`${styles.zx9Detail} ${styles.white} height100 childsMargin`}>
              <h1>ZX1<br />SPEAKER</h1>
              <p>Upgrade to premium speakers that are phenomenally built to deliver truly remarkable sound.</p>
              <Btn bg={"black"} color={"white"} size={'large'} text={'SEE PRODUCT'} />
            </div>
          </div>
        </section>
        <section className={`${styles.zx7Speaker} center marginTB b-radius childsMargin`}>
          <h2>ZX7 SPEAKER</h2>
          <Btn color={"black"} brColor={"black"} size={'large'} text={'SEE PRODUCT'} ghost={true} />
        </section>
        <section className={`${styles.yx1Earphones} flex margin`}>
          <div>
            <Image className="height100 b-radius" src="/images/home/desktop/image-earphones-yx1.jpg" width={540} height={588} />
          </div>
          <div className={`${styles.yx1Detail} center b-radius childsMargin`}>
            <h2>YX1 EARPHONES</h2>
            <Btn color={"black"} brColor={"black"} size={'large'} text={'SEE PRODUCT'} ghost={true} />
          </div>
        </section>
        <section>
          <BestGear />
        </section>
      </main>
    </>
  );
}
