import Head from 'next/head';
import styles from '@/styles/Home.module.css';
import Btn from '@/components/button/Btn';
import ProductCardContainer from '@/components/productCardContainer/ProductCardContainer';
import Image from 'next/image';
import BestGear from '@/components/bestGear/BestGear';

export default function Home() {
  return (
    <>
      <Head>
        <title>Audiophile</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/icon.png" />
      </Head>
      <main>
        <section className={styles.homeContainer}>
          <div className={`${styles.home} center childsMargin margin flex-column resCenter resWidth margin0`}>
            <strong className='newProduct'>NEW PRODUCT</strong>
            <h1 className={styles.white}>XX99 MARK || <br /> HEADPHONES</h1>
            <p style={{ color: 'var(--grey)' }}>Experience natural, lifelike audio and exceptional build quality made for the passionate music enthusiast.</p>
            <Btn link={"/headphones/xx99-mark-two-headphones"} bg={"orange"} size={'large'} text={'SEE PRODUCT'} />
          </div>
        </section>
        <section className={`${styles.productShow}`}>
          <ProductCardContainer />
        </section>
        <section className={`${styles.zx9SpeakerContainer} marginTB b-radius resCenter`}>
          <div className={`${styles.zx9Speaker} center width100 height100 resCenter flex-column`}>
            <picture className="center">
              <source media="(min-width: 992px)" srcSet="/assets/home/desktop/image-speaker-zx9.png" />
              <source media="(min-width: 480px)" srcSet="/assets/home/tablet/image-speaker-zx9.png" />
              <Image
                style={{ width: '28rem', height: '31rem' }}
                className="b-radius x9" src="/assets/home/mobile/image-speaker-zx9.png"
                width={500}
                height={500}
                alt="image of speaker"
              />
            </picture>
            <div className={`${styles.zx9Detail} ${styles.white} height100 childsMargin flex-column resWidth resCenter`}>
              <h1>ZX9<br />SPEAKER</h1>
              <p>Upgrade to premium speakers that are phenomenally built to deliver truly remarkable sound.</p>
              <Btn link={"/speakers/zx9-speaker"} bg={"black"} color={"white"} size={'large'} text={'SEE PRODUCT'} />
            </div>
          </div>
        </section>
        <section className="marginTB">
          <div className={`${styles.zx7Speaker} center b-radius childsMargin width100`}>
            <h2>ZX7 SPEAKER</h2>
            <Btn link={"/speakers/zx7-speaker"} color={"black"} brColor={"black"} size={'large'} text={'SEE PRODUCT'} ghost={true} />
          </div>
        </section>
        <section className={`${styles.yx1Earphones} flex margin flex-column childsMargin`}>
          <picture className="resWidth">
            <source media="(min-width: 992px)" srcSet="/assets/home/desktop/image-earphones-yx1.jpg" />
            <source media="(min-width: 480px)" srcSet="/assets/home/tablet/image-earphones-yx1.jpg" />
            <Image
              style={{ height: 'auto' }}
              className="b-radius resWidth  width100" src="/assets/home/mobile/image-earphones-yx1.jpg"
              width={540}
              height={588}
              alt="image of speaker"
            />
          </picture>
          <div style={{ height: 'auto' }} className={`${styles.yx1Detail} center b-radius childsMargin resWidth yx1Height`}>
            <h2>YX1 EARPHONES</h2>
            <Btn link={"/earphones/yx1-earphones"} color={"black"} brColor={"black"} size={'large'} text={'SEE PRODUCT'} ghost={true} />
          </div>
        </section>
        <section>
          <BestGear />
        </section>
      </main>
    </>
  );
}
