import Head from 'next/head'
import Image from 'next/image'
import { Divider } from 'antd';
import styles from '@/styles/Home.module.css'
import Header from '@/components/header/Header';

export default function Home() {
  return (
    <>
      <Head>
        <title>Audiophile</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/icon.png" />
      </Head>
      <main className='margin'>
        <section className={styles.home}>
          
        </section>
      </main>
    </>
  )
}
